// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvhDSu4hTVzv_j1fdN8zjrt5HpAZC9UD4',
    appId: '1:255036669928:web:b57ff6fea2ed962531ee5d',
    messagingSenderId: '255036669928',
    projectId: 'on-demand-7ed55',
    authDomain: 'on-demand-7ed55.firebaseapp.com',
    storageBucket: 'on-demand-7ed55.appspot.com',
    measurementId: 'G-WQCJTV1XVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKOCE72DztUi1WUuCg2bfyDg8CsbzkcV8',
    appId: '1:255036669928:android:420bda792fe01b9c31ee5d',
    messagingSenderId: '255036669928',
    projectId: 'on-demand-7ed55',
    storageBucket: 'on-demand-7ed55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb_ywjPwwfQYIoMTGvA_MzRaNCYSctj4w',
    appId: '1:255036669928:ios:ea018ecb07ee0fca31ee5d',
    messagingSenderId: '255036669928',
    projectId: 'on-demand-7ed55',
    storageBucket: 'on-demand-7ed55.appspot.com',
    iosBundleId: 'com.cube.onDemand',
  );
}
